name: 'Terraform CD'
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  deploy:
    name: 'Terraform CD'
    environment: production
    runs-on: ${{ vars.RUNS_ON }}

    defaults:
      run:
        shell: ${{ vars.DEFAULT_SHELL }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ vars.TERRAFORM_VERSION }}
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Create Terraform Plugin Cache Dir
      run: mkdir --parents $TF_PLUGIN_CACHE_DIR

    - name: Cache Terraform
      uses: actions/cache@v2
      with:
        path: ${{ env.TF_PLUGIN_CACHE_DIR }}
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
    
    - name: Terraform init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validation
      run: terraform validate -no-color

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
